### ISSUE TITLE
Update council page

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-community-handbook#186]
We need to update the council page with this information: https://www.mautic.org/mautic-council.

**Comment by AnukratiMehta** [comment]
@RCheesley I'd like to work on this. Please assign and share more details.

**Comment by mohamedsaajid** [comment]
Hey @RCheesley, I am interested to work on this, can you elaborate more on what changes you need? Cheers.

**Comment by RCheesley** [comment]
Thanks for the offer @AnukratiMehta and @mohamedsaajid but this already has a proposed fix in #187.
