### ISSUE TITLE
The TOC link to Step 2 of the Pull requests page is broken

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic-community-handbook#20]
Hey.

When viewing the Pull requests page on https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests the link to **Step 2: Feature? Check the roadmap & Feature Requests** in the TOC is broken, despite it working perfectly when viewing the page on https://github.com/mautic/mautic-community-handbook/blob/master/pages/13.contributing/02.developer/01.Code/02.Pull%20requests/docs.md

I looked into it and it turns out the TOC is linking to `#step-2-feature-check-the-roadmap--feature-requests`, which apparently works fine when viewing the page on GitHub, but apparently in Grav the working link to the section instead becomes `#step-2-feature-check-the-roadmap-feature-requests` (with only a single `-` after 'roadmap') and thus causing the TOC link to not work.

To make things even more confusing, I tried generating a TOC with the link from the source code - https://ecotrust-canada.github.io/markdown-toc/ - and according to that, the section link should be `#step-2--feature--check-the-roadmap---feature-requests` - i.e. with even more extra hyphens than the current link.

Since I don't have a ton of experience with neither Markdown nor Grav - and have no idea how to even test whether the Canada-approved section link works in Grav - I decided to just create a bug report instead. This might be an easy thing to fix, or it might be more complicated, tbh I have no idea.

**Comment by RCheesley** [comment]
I think this is probably a Grav-ism where the anchors plugin is trying to helpfully clean up the slugs where we have the & symbol.

I'll make an edit to the file to fix.
