### ISSUE TITLE
Navigation issue on "How is Mautic used?"

### ISSUE THREAD

**Issue by ahangarha** [mautic/mautic-community-handbook#73]
Clicking on Next button on "[How is Mautic used?](https://contribute.mautic.org/about/how-is-mautic-used)" page, takes me to [Code of Conduct](https://contribute.mautic.org/policies/code-of-conduct) in stead of "[How can I try Mautic?](https://contribute.mautic.org/about/how-can-i-try-mautic)".

Not sure how the system works but I guess the issue is related to lack of category in that page.

**Comment by RCheesley** [comment]
Ooh thanks for flagging that up - it looks like some of the pages are not using the 'type' of docs which means they do not show in the navigation.

**Comment by RCheesley** [comment]
Fixed with https://github.com/mautic/mautic-community-handbook/commit/bc9cf88eb453f8b100b34edbb77c1df1dde9c684 :)
